#!/bin/bash
#
while [ 1 ]
do
CHOICE=$(
whiptail --backtitle " Программа написана на whiptail"\
         --title "Редактирование и настройка herbstluftwm"\
         --menu "Клавишами верх/низ выберите справку и нажмите enter.
                 Для выхода выберите Exit." 0 0 20\
  "1)" "Следите за синтаксисoм и условиями herbstluftwm!"\
  "2)" "Установка"\
  "3)" "Версия и документация"\
  "4)" "Первая строка и комментарий"\
  "5)" "Первая команда на зелёном экране и сочетания клавиш"\
  "6)" "Показать скрипт сочетания клавиш"\
  "7)" "Путь к файлу конфигурации autostart"\
  "8)" "Показать файл autostart"\
  "9)" "Цвет самой начальной пустой панели"\
 "10)" "Установить обои на каждом теге"\
 "11)" "Просмотреть все атрибуты"\
 "12)" "Переименовать теги"\
 "13)" "startx"\
 "14)" "14"\
 "15)" "15"\
 "16)" "16"\
 "17)" "17"\
 "18)" "18"\
 "19)" "19"\
 "20)" "20"\
 "21)" "21"\
 "22)" "22"\
 "23)" "23"\
 "24)" "24"\
 "25)" "25"\
 "26)" "26"\
 "27)" "27"\
 "28)" "Сайты"\
 "29)" "Редактировать мой файл "\
 "30)" "Exit"\
 3>&2 2>&1 1>&3
)

result=$()
case $CHOICE in
       "1)")   
result="\n
 Следите за синтаксисoм!\n
 Для herbstluftwm в данном файле в параметре --textbox прописывать длинный путь к файлу"
        ;;
       "2)")   
result=" sudo apt-get install herbstluftwm\n
 либо:
 sudo apt update
 sudo apt install herbstluftwm\n
 "
        ;;
       "3)")   
result=" Версия:
 herbstluftwm --version\n
 Документация:
 man herbstluftwm\n
"
        ;;
       "4)")
result=" #
 любой текс после данного знака читается как комментарий
 за исключением первой строки:
 #!/bin/bash\n
"
        ;;
       "5)")   
result="\n
 Нажмите клавиши:
 alt enter\n
 и вы окажетесь в терминале.
 Дальше всё в ваших руках и голове.\n
 \n
 Re-load configuration | Повторно загрузить конфигурацию:
 alt shift r \n
 Переключение по тегам:
 alt 1 или alt 2, или alt 3, или alt цифра любого тега\n
 Разделить окна по горизонтали:
 alt u \n
 Разделить окна по вертикали:
 alt o \n
 Закрыть текущее окно:
 alt r\n
 Перемещение по оконам
 влево  : alt h
 вправо : alt l
 вверх  : alt k
 вниз   : alt j \n
 Завершить процесс, запущенный в текущем окне:
 alt shift c \n
 Изменить размер текущего окна
 меньше: alt ctrl j
 больше: alt ctrl k
 шире  : alt ctrl l
 уже   : alt ctrl h /n
 "
        ;;
       "6)")   
whiptail --textbox "/home/grannik/TeConfiguration/ConfigurationHerbstluftwm/keybindings.txt" 0 0 --scrolltext
        ;;
       "7)")
result="\n
 cd /etc/xdg/herbstluftwm/;clear;ls -la \n
 sudo su \n
 ne - это любой текстовый редактор в консоле
 ne autostart "
        ;;
       "8)")   
whiptail --textbox "/home/grannik/TeConfiguration/ConfigurationHerbstluftwm/autostart" 0 0 --scrolltext
        ;;
       "9)")  
result="xsetroot -solid '#330033'"
        ;;
       "10)")
whiptail --textbox "/home/grannik/TeConfiguration/ConfigurationHerbstluftwm/setWallpaperTag.txt" 0 0 --scrolltext
        ;;
       "11)")   
result="herbstclient attr"
        ;;
       "12)")
whiptail --textbox "/home/grannik/TeConfiguration/ConfigurationHerbstluftwm/tag.txt" 0 0 --scrolltext
        ;;
       "13)")   
result=" Запускает графическую среду Ubuntu в параллельном tty"
        ;;
       "14)")   
result="14"
        ;;
       "15)")
result="15"
        ;;
       "16)")
result="16"
        ;;
       "17)")
result="17"
        ;;
       "18)")
result="18"
        ;;
       "19)")   
result="19"
        ;;
       "20)")
result="20"
        ;;
       "21)")   
result="21"
        ;;
       "22)")   
result="22"
        ;;
       "23)")   
result="23"
        ;;
       "24)")   
result="24"
        ;;
       "25)")   
result="25"
        ;;
       "26)")
result="26"
        ;;
       "27)")   
result="27"
        ;;
        "28)")   
result=" https://www.herbstluftwm.org/
 https://www.herbstluftwm.org/tutorial.html
 https://bbs.archlinux.org/viewtopic.php?pid=1024618#p1024618
 https://gist.github.com/wdkrnls"
        ;;
        "29)")
ne whiptailEditing
        ;;
        "30)")   
exit
        ;;
esac
whiptail --msgbox "$result" 0 0
done
exit